### ISSUE TITLE
 hook

### ISSUE THREAD

**Issue by ivanpos2015** [btbd/hwid#1]
https://github.com/everdox/InfinityHook 
Probably this will be a better option than the standard IRP hook.

**Comment by btbd** [comment]
Correct me if I'm wrong, but wouldn't that only work for the disk driver? EVENT_TRACE_FLAG_DRIVER only enables DiskIo events according to [this](https://docs.microsoft.com/en-us/windows/win32/etw/event-trace-properties).

A trampoline hook directly on the driver's DeviceControl is another option.

**Comment by ivanpos2015** [comment]
need contact Discord send you file as an example

**Comment by btbd** [comment]
btbd#8494

**Comment by BerkanYildiz** [comment]
InfinityHook only works for usermode syscalls. So no.
Popular ACs sends direct IoCallDriver or build IRPs to sent them directly from kernel, for the most important requests (EAC for example, does not get everything from UM, I'm not sure about BE).

**Comment by btbd** [comment]
@ivanpos2015 I've added an alternative to the standard IRP hook in [this branch](https://github.com/btbd/hwid). Will do more testing before merging.

**Comment by BerkanYildiz** [comment]
I thought both ACs detected read+executable sections patches (?)
I don't think you should bother updating the hooking method anyway, it's a story that will never end.

**Comment by fisherprice84** [comment]
it seems executing the driver returns null data.  anyone come across this?

**Comment by btbd** [comment]
@anotherfinemess84 What do you mean exactly? I do null some queries rather than entirely fake as it was sufficient for my use case.

**Comment by anotherfinemess84** [comment]
Seems it’s not spoofing the max of the active connection only other devices
like disconnected vpn.

You have an Email I can send some things to?

**Comment by btbd** [comment]
@anotherfinemess84 Just message me on Discord. I posted it above.

I'm going to close this issue for now. I'll leave the alternative hook in the other branch, but other implementations are up to the user as this repo is supposed to serve as an example of handling common queries.
