### ISSUE TITLE
World of Wracraft HWID Changer?

### ISSUE THREAD

**Issue by slitec** [btbd/hwid#10]
Hello,

does your HWID-Changer work with World of Warcraft? 

I'll just throw in the device id they use in WoW which is sent through the authentication the first time.
`Device-Id:{  
   "RGKY":xxx, // RtlGenRandom (Identify)
   "CPGE":xxx, // GetACP
   "ULNG":xxx, // GetUserDefaultLangID
   "SLNG":xxx, // GetSystemDefaultLangID
   "CNME":xxx, // GetComputerNameW
   "UNME":xxx, // GetUserNameW
   "UTCO":xxx, // GetTimeZoneInformation
   "CARC":xxx, // wProcessorArchitecture
   "CREV":xxx, // wProcessorRevision
   "CLVL":xxx, // wProcessorLevel
   "PMEM":xxx, // lpMinimumApplicationAddress >> 20 ?!
   "PSZE":xxx, // dwActiveProcessorMask >> 20 ?!
   "OVER":xxx, // cpuid start
   "CVRA":xxx, .
   "CFTC":xxx, .
   "CFTD":xxx, .
   "CEFC":xxx, .
   "CEFD":xxx, .
   "CBRD":xxx, // cpuid end
   "CVEN":xxx, // RtlGetVersion (%d.%d.%d.%d %s)
   "ANME":xxx, // GetAdaptersInfo.AdapterName
   "ADSC":xxx, // GetAdaptersInfo.Description
   "MAC":xxx   // GetAdaptersInfo.Address
}`

**Comment by btbd** [comment]
It changes a few things in that list, but not all. Test it yourself. I don't do anything with WoW.
