### ISSUE TITLE
how is it meant to be used?

### ISSUE THREAD

**Issue by ashrockd** [btbd/hwid#12]
What a ride!
when I first saw this I was wondering where is the exe file, but then I read that I have to compile. I downloaded VS and began compiling. It gave a bunch of errors and after troubleshooting though each error another would pop up. I was somehow able to compile the kernel HWID Spoofer and got a kernel.sys. After a bit of research I learnt that drivers don't come in exe they come in sys. I figured out how to load them through cmd by disabling intergrity checks and enabling test signing.

Now to the real issue. Once I load the driver through CMD, it starts as a service. It does serves my purpose and mitigates the HWID detection issues; 
but
well is that it ? 
There are other commands, I might not know of?
if I sc stop the kernel.sys and sc start it again, will it generates a different HWID?
Is there anything else I should know?

PS: Yes I'm a complete noob when it comes to programming. While troubleshooting through compiling the kernel I got to know about kernel mode/user mode applications, windows internals, and many other things. It arose my interest in learning programming ever more. Hopefully one day I should be able to contribute to your project.

**Comment by fatrolls** [comment]
you need to compile the user app it will give you EXE that runs the Kernel

**Comment by btbd** [comment]
@fatrolls Incorrect. The kernelmode and usermode components are completely independent.

@ashrockd The only other component besides the kernelmode driver is the usermode program is to mitigate registry and file tracking. How this is "meant to be used" is up to you. You could load the driver and run the usermode program if that suites you. Or use this as a learning example of handling certain queries and handling common tracking methods.

**Comment by OverheadOcean** [comment]
@btbd do you have discord theres some stuff i wanna ask you
