### ISSUE TITLE
Completly destroys Windows Licensing system

### ISSUE THREAD

**Issue by themaoci** [btbd/hwid#16]
After using it you will need to reinstall windows (cause it has some fault codes included which if you dont fix you will end up with `Error: 0xC0000022 ... Windows non-core edition`
and also trying to activate it or restart will lead you to conclusion that windows version is changed to `.` or other character.

```Unhandled exception at 0x00007FFB487AE173 (msvcrt.dll) in licensingdiag.exe: 0xC0000005: Access violation reading location 0x0000000000000000.```

I was using Modded windows in this case named `Win jg10 pro x64`
Download link:
https://mega.nz/#!R8gSAQAY!BMLcEgVTNQl-GVldBcX-i6GbzprlRUC_WXSzmE2Y9X8
made by srom-otnik (a guy from Poland, so get aware it has only Polish language included and you will need to install in via Polish UI and install language pack after instalation is finished)

**Comment by btbd** [comment]
The usermode program will change registry keys related to activation and https://github.com/btbd/hwid/issues/15 as they can be used for tracking.

This repository was intended to be a collection of handling queries and common tracking files. You can freely change what the usermode program does if you don't want it to touch anything with activation, but it was intended to be as general as possible.
