### ISSUE TITLE
How to know if the software is safe? 🤔 

### ISSUE THREAD

**Issue by TheMineAxel** [btbd/hwid#18]
Hello,

Several months ago, I looked for how to get unban from apex legend i used spoofer and I got ban on fortnite. But after several months, I m unban for no reason. 

Very soon I will need a spoofer for rust that uses easy anti cheat like fortnite. How to know if the software is safe for epic game
And if its detected how to change the software to unflag it??

I know some process are insta-banned like changing id driver with "hook" software i dont rly know what does that mean but it's detected 🤷‍♂️

**Comment by btbd** [comment]
This project is detected out of the box for EAC/BE. This repository was designed to be a collection of handling queries and traces rather than a one-stop solution for all.
