### ISSUE TITLE
Libraries Required

### ISSUE THREAD

**Issue by ProdigyOfficial** [btbd/hwid#2]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8040	Spectre-mitigated libraries are required for this project. Install them from the Visual Studio installer (Individual components tab) for any toolsets and architectures being used. Learn more: https://aka.ms/Ofhn4c	User	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	425

Can i get a screenshot of your extra components on visual studio installer?

Thanks.

**Comment by fisherprice84** [comment]
turn off spectre mitigation in C++ > Code Generation
