### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by Tibzzy** [btbd/hwid#22]
After compiling the driver successfully, loading it with any mapper would result in a BSOD regardless of the windows versions I have tested on (all which match the supported range).

Tested on 1809, 1903, 1909

Edit: Secure boot is off btw

**Comment by btbd** [comment]
@Tibzzy Can you provide a crash dump?

**Comment by 2sad32** [comment]
> > loading it with any mapper would result in a BSOD
> 
> This driver cannot be manually mapped out of the box. Remove the references to the invalid driver object.

Tell me how to do this pls
