### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by LuckerCracker** [btbd/hwid#3]
Your spoofer does not work on Windows 1803 (17134.950) (I get out a blue screen). Can I somehow fix it myself?

**Comment by btbd** [comment]
You can follow with a kernel debugger and VM or look at the crash dump to see where it went wrong.

**Comment by LuckerCracker** [comment]
Well, does your spoofer change these values ​​on the hard drive?
![Снимок](https://user-images.githubusercontent.com/49616881/63495496-0a358780-c4d1-11e9-9ecd-136de8e741b0.PNG)

**Comment by btbd** [comment]
It will only change the serial number for harddrives. Not sure what you're trying to show in that screenshot.

**Comment by LuckerCracker** [comment]
In the screenshot I need to change Model ID, SerialNumber, Firmware

**Comment by btbd** [comment]
Well, you'll have to implement the others yourself. Have you made any progress on your original issue?

**Comment by LuckerCracker** [comment]
No
