### ISSUE TITLE
None_paged_fault_area BSOD(win10 1803)

### ISSUE THREAD

**Issue by SeekingFunChild** [btbd/hwid#4]
I'm sure the problem is caused by SpoofNIC function，How can I fix it?

**Comment by btbd** [comment]
It's likely an issue with one of the signatures. From the crash dump, can you say what line causes the BSOD?

**Comment by SeekingFunChild** [comment]
Debugging on VMware Win10：

PNDIS_IF_BLOCK block = *(PNDIS_IF_BLOCK *)((PBYTE)filter + ndisFilter_IfBlock_offset); //This statement cause BSOD.

Find the Reson:

PDWORD ndisFilter_IfBlock = FindPatternImage(base, "\x48\x85\xFF\x0F\x84\x00\x00\x00\x00\x4C\x8B", "xxxxx????xx");

Find sign in ndis.sys:

.text:000001C0005442                 test    rdi, rdi
.text:00000001C0005445                 jz      loc_1C0005518
.text:00000001C000544B                 mov     r14, [rbp+110h+var_D0]

Is this Singnature incorrect?If it is correct:

DWORD ndisFilter_IfBlock_offset = *(PDWORD)((PBYTE)ndisFilter_IfBlock + 12);
I think this statement is incorrect.It should be:
DWORD ndisFilter_IfBlock_offset = *(PBYTE)((PBYTE)ndisFilter_IfBlock + 12);

But with this modification:
PIF_PHYSICAL_ADDRESS_LH addr = &block->ifPhysAddress; //addr will be 0
SpoofBuffer(SEED, addr->Address, addr->Length); //cause BSOD

**Comment by SeekingFunChild** [comment]
I have solved this issue cause by incorrect signature.

PDWORD ndisFilter_IfBlock = FindPatternImage(base, "\x48\x85\xFF\x0F\x84\x00\x00\x00\x00\x4C\x8B", "xxxxx????xx");

correct sign is "\x48\x85\xF6\x0F\x84\x00\x00\x00\x00\x4C\x8B"

**Comment by btbd** [comment]
Thanks for the info! The new signature will have to be adjusted to also work for the other Windows versions but I will fix that later once I download 1803 ISO.

**Comment by SeekingFunChild** [comment]
Yes,"\x48\x85\xF6\x0F\x84\x00\x00\x00\x00\x4C\x8B" is just for win10 1607,which installed in VMWare

**Comment by SeekingFunChild** [comment]
PDWORD ndisFilter_IfBlock = FindPatternImage(base, "\x48\x85\x00\x0F\x84\x00\x00\x00\x00\x00\x8B\x00\x00\x00\x00\x00\x33", "xx?xx?????x???xxx");

This signature is  working on 1607 and 1803, maybe other Win10 vesions are the same.

**Comment by btbd** [comment]
Also works on 1507, 1809, and 1903. Thanks for the contribution.
