### ISSUE TITLE
Please help MSBuild Error MSB8020

### ISSUE THREAD

**Issue by gsansanwal** [btbd/hwid#5]
Please help MSBuild Error MSB8020

everything installed correctly still getting error windowskernelmode10.0 installation

**Comment by btbd** [comment]
Install v140 build tools for VS or change the project's platform toolset.

**Comment by gsansanwal** [comment]
Thanks for your support problem solved but now m stuck on "Please select a valid target machine for deployment from the project property page". but when i select then i unable to connect to remove connection just refused connection...
