### ISSUE TITLE
how to solve this issue

### ISSUE THREAD

**Issue by gsansanwal** [btbd/hwid#6]
"Please select a valid target machine for deployment from the project property page". but when i select then unable to connect error just refused connection...

Installing necessary components...
Failed operation: An error occurred while connecting from the remote machine.
Error: 10061 (ConnectionRefused)
Error message: No connection could be made because the target machine actively refused it

**Comment by btbd** [comment]
Stop creating issues for your VS problems that can be Googled. I am not tech support.
