### ISSUE TITLE
BSOD Win 10 1903

### ISSUE THREAD

**Issue by Mirko1273** [btbd/hwid#8]
When i run the driver with kdmapper i get Blue screen (BSOD) and error something like KERNEL SECURITY CHECK FAILURE can you pls help me fix this?

**Comment by btbd** [comment]
If you are going to manually map it then remove references to the invalid driver object.

**Comment by Mirko1273** [comment]
So i dont understand can you guide me to fix it please

**Comment by btbd** [comment]
I’m not going to spoon-feed you. You clearly have a lot to learn.

**Comment by Mirko1273** [comment]
can you atleast tell me where to start for this driver please

**Comment by morelli690** [comment]
go to the place u got link to this repo from, u will find all u need in there.
